### ISSUE TITLE
Update CI fuzz tests to not use `set-output`

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/shescape#488]
# Task

## Description

[The fuzz tests currently in the CI](https://github.com/ericcornelissen/shescape/blob/f896f20ab513bd1d17625189837e09511172d605/.github/workflows/reusable-fuzz.yml#L112-L132) use `set-output` (as `echo "::set-output name=xxx::$yyy"`), which is an GitHub Actions' feature that [has been deprecated an may be disabled in the future](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

To ensure the fuzz tests in the CI keep working, they should be updated to not use `set-output` (or `save-state`) anymore.

Based on https://github.com/github/codeql-action/compare/v2.1.27...v2.1.28 it looks like changing the workflow as follows _should_ work:

```diff
- echo "::set-output name=xxx::$yyy"
+ echo "xxx=$yyy" >> $GITHUB_OUTPUT
```

**Comment by samkcrespo** [comment]
Can I be assigned to this?

**Comment by ericcornelissen** [comment]
Done @samkcrespo, looking forward to your Pull Request

**Comment by samkcrespo** [comment]
> 

I am not finding any documenation regarding if line 131 should have >> $GITHUB_OUTPUT after or before $EXIT_CODE

**Comment by ericcornelissen** [comment]
@samkcrespo, `>> $GITHUB_OUTPUT` should come **before** the `$EXIT_CODE`.

For some background, `>>` is a shell operator. You can read more about it online, for example [this ask ubuntu answer](https://askubuntu.com/a/382796) might explain it some more :slightly_smiling_face:

**Comment by ericcornelissen** [comment]
Worked as expected in https://github.com/ericcornelissen/shescape/actions/runs/3298801923
